### ISSUE TITLE
Consider listing our meetup with the CNCF

### ISSUE THREAD

**Issue by castrojo** [orchestructure/projects#5]
https://www.meetup.com/pro/cncf/

**Comment by InAnimaTe** [comment]
From that meetup page:

> Groups listed below have identified Cloud Native Computing Foundation (CNCF) and/or CNCF-hosted projects as topics covered throughout the year. While groups may opt to cover additional Open technologies, the presumption is that all have at least a working level knowledge, and primary support for, CNCF projects / principles.

> If you want your meetup added to this list, send an email to meetups@cncf.io!

Technically, we've discussed a few of the CNCF projects in the past and plan to discuss many more this year. In terms of awareness, the co-organizers certainly know about the CNCF and we can certainly talk more about it at every meeting. In that context, I think we'd fit well as a "CNCF meetup" which would also work in tandem with ambassadorship we're going for.

@castrojo you're probably most apt to execute on this ;)

**Comment by castrojo** [comment]
@InAnimaTe close this when you get the form back pls.

**Comment by castrojo** [comment]
We're listed on there now, woo!
